expanded_households_files: # synthetic_households from PopSim
  - "data/synthetic_households.csv"

mid_hh_file: "data/MiD2017_Haushalte_gefiltert_RStar71.csv"
mid_persons_file: "data/MiD2017_Personen_gefiltert_RStar71.csv"
mid_trips_file: "data/MiD2017_Wege_edited.csv"

id_columns:
  household_mid_id_column: "H_ID"
  household_popsim_id_column: "household_id"
  person_id_column: "HP_ID"
  # In MiD, the leg id is not unique. If you provide leg_non_unique_id_column, a unique id will be created.
  # If your data already has a unique leg ids, just provide the column name in leg_id_column
  leg_non_unique_id_column: "W_ID"
  leg_id_column: "HPW_ID" # Will be created if it doesn't exist and leg_non_unique_id_column is provided

# Declare only columns that are needed for processing (you can declare more, but that's a waste of memory and time)
hh_columns:

person_columns:
  person_age: "HP_ALTER"
  car_avail: "P_VAUTO"
  has_license: "P_FS_PKW"

leg_columns:
  leg_target_activity: "W_ZWECK"
  leg_main_mode: "hvm_imp"
  leg_start_time: "W_SZ"
  leg_end_time: "W_AZ"
  leg_duration_minutes: "wegmin"
  leg_distance: "wegkm"

value_maps:
  activities:
    home: 8
    education: [3,11,12]
    work: 1 # Work is considered the main activity, else education
  car_availability:
    never: 3
  license:
    "yes": 1
    "no": 2
    unknown: 9
    adult_over_16_proxy: 206
    person_under_16: 403
  mode:
    car: 4
    bike: 2
    walk: 1
    pt: 5
    ride: 3
    other:
    unknown:

lowest_level_geography: "BAUBLOCKNR"

average_activity_times_minutes:
  work: 30
  lunch: 45
  gym: 50
  shopping: 25
  meeting: 35

# Leave empty to write no file, else e.g.: "output/full_population_frame.csv"
population_analysis_output_file: "output/full_population_frame.csv"