
sample_size: 0.5 # 0.1 = 10% of the population
n_closest_cells: 5 # Number of cell candidates to consider for main activity location



input_files:
  expanded_households_files: # synthetic_households from PopSim
    - "data/synthetic_households1.csv"


  mid_hh_file: "data/MiD2017_Haushalte_gefiltert_RStar71.csv"
  mid_persons_file: "data/MiD2017_Personen_gefiltert_RStar71.csv"
  mid_trips_file: "data/MiD2017_Wege_edited.csv"
  buildings_in_lowest_geography_with_weights_file: "data/houses_with_weights.csv"

  shape_boundary_file: "data/shapes/Region Hannover.shp"
  tt_matrix_cells_file: "data/shapes/tt_matrix_cells.shp"
  tt_matrix_file: "data/tt_matrix.csv"

# Leave empty to write no file, else e.g.: "full_population_frame.csv"
output_files:
  population_analysis_output_file: "full_population_frame.csv"
  matsim_plans_file: "population.xml"

id_columns:
  household_mid_id_column: "H_ID"
  household_popsim_id_column: "household_id"
  person_id_column: "HP_ID"
  # In MiD, the leg id is not unique. Provide leg_non_unique_id_column, a unique id will be created.
  # If your data already has unique leg ids, feel free to provide leg_id_column,
  # but a sortable leg_non_unique_id_column must be provided anyway.
  leg_non_unique_id_column: "W_ID"  # Expected to be sortable in the order of the trip legs
  leg_id_column: "HPW_ID" # Will be created if it doesn't exist and leg_non_unique_id_column is provided
  tt_matrix_cell_id_column: "cell_id"

# Declare only columns that are needed for processing (you can declare more, but that's a waste of memory and time)
geography_columns:  # largest to smallest, as in the popsim settings
- WELT
- STAAT
- STADTTLNR
- BAUBLOCKNR
lowest_level_geography: "BAUBLOCKNR"

hh_columns:
  car_in_hh_column: "auto"
  region_type_column: "RegioStaR7"

person_columns:
  person_age: "HP_ALTER"
  car_avail: "P_VAUTO"
  has_license: "P_FS_PKW"

leg_columns:
  leg_target_activity: "W_ZWECK"
  leg_main_mode: "hvm_imp"
  leg_start_time: "W_SZ"
  leg_end_time: "W_AZ"
  leg_duration_minutes: "wegmin"
  leg_distance: "wegkm"

value_maps: # Values may usually be left empty if they don't exist in the data
  activities:
    work: 1
    business: 2
    education: 3
    shopping: 4
    errands: 5
    pick_up_drop_off: 6
    leisure: 7
    home: 8
    return_journey: 9
    other: 10
    early_education: 11 # Preschool, Grundschule
    daycare: 12 #Kiga, Kita
    accompany_adult: 13
    sports: 14
    meetup: 15 # Visit friends
    lessons: 16 # Music, dance, etc., not school
    unspecified: 99
  car_availability:
    never: 3
  car_in_hh:
    "yes": 1
    "no": 0
  license:
    "yes": 1
    "no": 2
    unknown: 9
    adult_over_16_proxy: 206
    person_under_16: 403
  modes:
    car: 4
    bike: 2
    walk: 1
    pt: 5
    ride: 3
    other:
    undefined:

average_activity_times_minutes:
  work: 30
  lunch: 45
  gym: 50
  shopping: 25
  meeting: 35

misc:
  dun_dun_duuun: 1 # Play sound on error