
sample_size: 0.02 # 0.1 = 10% of the population
n_closest_cells: 10 # Number of cell candidates to consider for main activity location
default_slack_factor: 1.5
sigmoid_beta: -0.15
sigmoid_delta_t: 1200  # Seconds

input_files:
  expanded_households_files: # synthetic_households from PopSim
    - "data/synthetic_households1.csv"

  enhanced_mid_file: "data/enhanced_frame_final.csv"

  mid_hh_file: "data/MiD2017_Haushalte.csv"
  mid_persons_file: "data/MiD2017_Personen.csv"
  mid_trips_file: "data/MiD2017_Wege_edited.csv"
  buildings_in_lowest_geography_with_weights_file: "data/houses_with_weights.csv"

  capa_cells_csv_path: "data/region_hanover_potentials.csv"
  capa_cells_shp_path: "data/shapes/RH_useful__zone.SHP"

  shape_boundary_file: "data/shapes/Region Hannover.shp"
  tt_matrix_cells_file: "data/shapes/tt_matrix_cells.shp"
  tt_matrix_car_files:
    - "data/TTmatrices/hour_Min_0_Max 1car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_1_Max 2car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_2_Max 3car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_3_Max 4car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_4_Max 5car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_5_Max 6car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_6_Max 7car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_7_Max 8car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_8_Max 9car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_9_Max 10car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_10_Max 11car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_11_Max 12car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_12_Max 13car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_13_Max 14car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_14_Max 15car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_15_Max 16car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_16_Max 17car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_17_Max 18car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_18_Max 19car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_19_Max 20car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_20_Max 21car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_21_Max 22car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_22_Max 23car_travel_times.csv.gz"
    - "data/TTmatrices/hour_Min_23_Max 24car_travel_times.csv.gz"

  tt_matrix_pt_files:
    - "data/TTmatrices/pt_hour_Min_0_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_1_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_2_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_3_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_4_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_5_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_6_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_7_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_8_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_9_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_10_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_11_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_12_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_13_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_14_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_15_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_16_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_17_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_18_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_19_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_20_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_21_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_22_Max pt_travel_times.csv.gz"
    - "data/TTmatrices/pt_hour_Min_23_Max pt_travel_times.csv.gz"

  tt_matrix_walk_file: "data/TTmatrices/walk_travel_times.csv"
  tt_matrix_bike_file: "data/TTmatrices/bike_travel_times.csv"

  slack_factors_file: "data/slack_factors.csv"

# Leave empty to write no file, else e.g.: "full_population_frame.csv"
output_files:
  population_analysis_output_file: "full_population_frame.csv"
  matsim_plans_file: "population.xml"

id_columns:
  household_mid_id_column: "H_ID"
  household_popsim_id_column: "household_id"
  person_id_column: "HP_ID"
  # In MiD, the leg id is not unique. Provide leg_non_unique_id_column, a unique id will be created.
  # If your data already has unique leg ids, feel free to provide leg_id_column,
  # but a sortable leg_non_unique_id_column must be provided anyway.
  leg_non_unique_id_column: "W_ID"  # Expected to be sortable in the order of the trip legs
  leg_id_column: "HPW_ID" # Will be created if it doesn't exist and leg_non_unique_id_column is provided
  tt_matrix_cell_id_column: "cell_id"

# Declare only columns that are needed for processing (you can declare more, but that's a waste of memory and time)
geography_columns:  # largest to smallest, as in the popsim settings
  - WELT
  - STAAT
  - STADTTLNR
  - BAUBLOCKNR
lowest_level_geography: "BAUBLOCKNR"

hh_columns:
  car_in_hh_column: "auto"  # "auto" is a boolean column, 1 = yes, 0 = no
  number_of_cars_column: "H_ANZAUTO"
  region_type_column: "RegioStaR7"

person_columns:
  person_age: "HP_ALTER"
  car_avail: "P_VAUTO"
  has_license: "P_FS_PKW"
  number_of_legs: "anzwege1" # Legs without rbW

leg_columns:
  leg_target_activity: "W_ZWECK"
  leg_main_mode: "hvm_imp"
  leg_start_time: "W_SZ"
  leg_end_time: "W_AZ"
  leg_duration_minutes: "wegmin_imp2"  # Legs without rbW
  leg_distance: "wegkm_imp"
  first_leg_starts_at_home: "W_SO1"

enhancement_columns: # Columns created by the enhancement module
  random_location: "random_location"
  activity_duration_seconds: "activity_duration_seconds"
  number_of_legs_incl_imputed: "number_of_legs_incl_imputed"
  imputed_time: "imputed_time"
  imputed_leg: "imputed_leg"
  list_of_cars: "car_list"
  leg_from_activity: "leg_from_activity"

processing_columns: # Used by several pipelines. Cols aren't in the outputs, but are in the final analysis dump.
  unique_leg_id: "unique_leg_id"
  unique_household_id: "unique_household_id"
  unique_person_id: "unique_person_id"


value_maps: # Values may usually be left empty if they don't exist in the data
  activities:
    work: 1
    business: 2
    education: 3
    shopping: 4
    errands: 5
    pick_up_drop_off: 6
    leisure: 7
    home: 8
    return_journey: 9
    other: 10
    early_education: 11 # Preschool, Grundschule
    daycare: 12 #Kiga, Kita
    accompany_adult: 13
    sports: 14
    meetup: 15 # Visit friends
    lessons: 16 # Music, dance, etc., not school
    unspecified: 99
  car_availability:
    never: 3
  car_in_hh:
    "yes": 1
    "no": 0
  license:
    "yes": 1
    "no": 2
    unknown: 9
    adult_over_16_proxy: 206
    person_under_16: 403
  modes:
    car: 4
    bike: 2
    walk: 1
    pt: 5
    ride: 3
    other:
    undefined:
  misc:
    first_leg_starts_at_home: 1

misc:
  dun_dun_duuun: 0 # Play sound on error